name: GeekSeat Test Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      #Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 3.1
      # Run tests
      - name: Test
        run: dotnet test
      #Publish
      - name: Publish 
        run: dotnet publish GeekSeat.csproj -c Release -o release --nologo
        
     #Publish to GithubPages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
      
