name: GeekSeat Test Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      #Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 3.1
      # Run tests
      - name: Test
        run: dotnet test
      #Publish
      - name: Publish 
        run: dotnet publish GeekSeat.csproj -c Release
      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PUBLISH_GEEKSEAT }}
          publish_branch: gh-pages
          publish_dir: bin/Release/netcoreapp3.1/publish/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
